# Generated by Django 5.2.4 on 2026-03-27 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_configbot_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app1.configbot'),
        ),
        migrations.AddField(
            model_name='whatsappsession',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='app1.configbot'),
        ),
        migrations.AlterField(
            model_name='configbot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='app1.user'),
        ),
    ]
