# Generated by Django 5.2.4 on 2026-03-27 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_whatsappmessage_bot_whatsappsession_bot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configbot',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='app1.user'),
        ),
    ]
