# Generated by Django 5.2.4 on 2026-03-27 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_configbot_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Archivo de contexto (PDF, DOC, DOCX, XLS, XLSX)', upload_to='context_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_files', to='app1.configbot')),
            ],
        ),
    ]
