# Generated by Django. Add the plan field to User
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('app1', '0006_contextfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(
                max_length=20,
                choices=[('base', 'Base (1 bot)'), ('especial', 'Especial (3 bots)'), ('premium', 'Premium (ilimitado)')],
                default='base',
            ),
        ),
    ]
