# Generated by Django 5.2.4 on 2026-05-04 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_agente_departamento_delete_prueba_remove_user_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agentes', to='app1.user'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='app1.user'),
        ),
    ]
