# Generated by Django 5.2.4 on 2026-05-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_agente_owner_departamento_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agente',
            name='departamento',
        ),
        migrations.AddField(
            model_name='agente',
            name='departamentos',
            field=models.ManyToManyField(blank=True, related_name='agentes', to='app1.departamento'),
        ),
    ]
