# Generated by Django 5.2.4 on 2026-06-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_configbot_api_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='configbot',
            name='max_response_chars',
            field=models.IntegerField(default=1000, help_text='Límite de caracteres en respuestas del bot'),
        ),
    ]
