# Generated by Django 5.2.4 on 2026-06-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_configbot_max_response_chars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configbot',
            name='api_key',
            field=models.TextField(blank=True, help_text='API Key del proveedor seleccionado (cifrada)', null=True),
        ),
    ]
