# Generated by Django 5.2.4 on 2026-06-12 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_configbot_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='configbot',
            name='inactividad_minutos',
            field=models.IntegerField(default=0, help_text='Minutos de inactividad para cerrar conversación (0 = desactivado)'),
        ),
        migrations.AddField(
            model_name='configbot',
            name='mensaje_cierre',
            field=models.CharField(blank=True, default='', help_text='Mensaje al cerrar conversación por inactividad', max_length=500),
        ),
        migrations.CreateModel(
            name='ClienteConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_jid', models.CharField(blank=True, max_length=200)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('plan_interes', models.CharField(blank=True, max_length=200)),
                ('resumen', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='app1.configbot')),
            ],
        ),
    ]
