# Generated by Django 5.2.4 on 2026-03-28 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_user_plan'),
        ('app2', '0005_delete_configbot_delete_whatsappmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IAAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('deepseek', 'DeepSeek'), ('chatgpt', 'ChatGPT'), ('gemini', 'Gemini'), ('easybot', 'EasyBot (proxy)')], max_length=30, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserIAAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('user_api_key', models.CharField(blank=True, max_length=200, null=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='app2.iaapi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_access', to='app1.user')),
            ],
            options={
                'unique_together': {('user', 'api')},
            },
        ),
    ]
